---
title: "AutoPollS Analysis Verification"
author: 'Acacia Tang'
date: '2024-06-27'
output: html_document
---
```{r, include=FALSE}
library(dplyr)
library(lubridate)
library(stringr)
library(gridExtra)
library(ggplot2)
```
### Directories with results
```{r}
CSVdir <- '/Volumes/NetBackup/Shade_NewModel/CSV'
CropsDir <- '/Volumes/NetBackup/Shade_NewModel/Crops'
```

```{r, echo=FALSE}

#Get list of '*_bees.csv') files output from model
CSVs <- list.files(CSVdir, pattern = paste0('_bees.csv', "$"), full.names = TRUE)
if (length(CSVs) == 0) {
  stop("No files found with the specified suffix.")
}

# Read and combine CSV files
allBees <- lapply(CSVs, read.csv) %>%
  bind_rows()

#Aggregate Apis and Bombus into genus-level categories
allBees$class1[grepl('Bombus', allBees$class1)] <- 'Bombus'
allBees$class1[grepl('Apis', allBees$class1)] <- 'Apis'


#Add datetime
pull_time <- function(fname){
  x <- strsplit(fname, '_')[[1]][4] #Take out the fourth element of the filename after separating by hyphens
  return(x)
}

#Pull timestamps from filename
allBees$time <- sapply(allBees$filename, pull_time)

#Create reference start time
start.date <- parse_date_time('2023-01-01 00:00:00', "%Y-%m-%d %H:%M:%S")
allBees$timestamp <- paste(allBees$date, allBees$time, sep = "_")
allBees$timestamp <- parse_date_time(allBees$timestamp, "ymd HMS")

#Return timestamp vector as a numeric time since start date (in days)
allBees$time.num <- as.numeric(difftime(allBees$timestamp, start.date, units = 'days'))
```

```{r data viz}
#Visualize confidence values
#ggplot(allBees, aes(x = conf, y = prob1))+stat_density_2d_filled(show.legend = FALSE)

#Detections over time
ggplot(allBees, aes(time.num)) + geom_density()
```

### occurrence of insect groups
```{r inspect classes in your dataset}
occurrence <- data.frame(sort(table(allBees$class1), decreasing = TRUE))
print(occurrence)
plot(occurrence)

## Alternative: subset to a particular group of species
data_subset <- subset(allBees, conf > 0.8 & prob1 > 0.8)
sort(table(data_subset$class1))

```

### Parameters to verify
```{r set parameters for }
detectionConf <- 0.8
classificationConf <- 0.8
minoccurrence <- 100 #must have this many occurrences to run verification
sampleN <- 100 #number of files to copy for verification
outDir <- '/Users/jamescrall/Desktop/shade_verification_data_2'

#Subset to specific species
group_list <- c('Coleoptera', 'Diptera', 'Bombus', 'Apis', 'Syrphidae', 'Lepidoptera', 'Diptera', 'Wasp')
```

```{r output sample images for verification, echo = FALSE}
if (!file.exists(outDir)) {
    dir.create(outDir)
}

#Subset to species with enough occurrences and 
runMe <- occurrence[occurrence$Freq > minoccurrence & occurrence$Var1 %in% group_list,]

verify <- function(x) {
    name <- as.character(x[1,1])
    print(name)

    if (!file.exists(file.path(outDir, name))) {
        dir.create(file.path(outDir, name))
    }
    if (!file.exists(file.path(outDir, name, 'positive'))) {
        dir.create(file.path(outDir, name, 'positive'))
    }

    if (!file.exists(file.path(outDir, name, 'negative'))) {
        dir.create(file.path(outDir, name, 'negative'))
    }


    sightings <- allBees[allBees$class1 == name,]

    sightings$good <- sightings$conf > detectionConf & sightings$prob1 > classificationConf

    good <- sightings[sightings$good,]
    bad <- sightings[!sightings$good,]

    if (nrow(bad) < sampleN) {
        negatives <- bad
    } else {
        negatives <- bad[sample(nrow(bad), sampleN, replace = FALSE),]
    }
     
    if (nrow(good) < sampleN) {
        positives <- good
    } else {
        positives <- good[sample(nrow(good), sampleN, replace = FALSE),]
    }

    writePosFiles <- function(row) {
        subdir = paste(c(as.character(row['unitID']), as.character(row['cameraID']), as.character(row['date'])), collapse="_")
        path <- file.path(CropsDir,subdir, as.character(row['filename']))
        file.copy(path, file.path(outDir, name, 'positive', as.character(row['filename'])))
    }

    writeNegFiles <- function(row) {
        subdir = paste(c(as.character(row['unitID']), as.character(row['cameraID']), as.character(row['date'])), collapse="_")
        path <- file.path(CropsDir,subdir, as.character(row['filename']))
        file.copy(path, file.path(outDir, name, 'negative', as.character(row['filename'])))
    }

    apply(negatives, 1, writeNegFiles)
    apply(positives, 1, writePosFiles)
}

verifyRows <- by(runMe, seq_len(nrow(runMe)), verify)

```

```{R visualize detections across days by group}

#Subset to detections above a threshold
data_subset <- subset(allBees, conf > 0.5 & prob1 > 0.5 & class1 %in% group_list)
data_subset$unique.camera <- paste(data_subset$unitID, data_subset$cameraID, sep = "_")

#Create plot of detections over time by camera
p1 <- ggplot(data_subset, aes(x = time.num, y = unique.camera, colour = class1))+geom_point(cex = 1.5, alpha = 0.2)

#Overall density of detections by group
p2 <- ggplot(data_subset, aes(x = time.num, colour = class1)) + geom_density() +xlim(182,240)

#Plot
grid.arrange(p1,p2)
```